export const messages = {
  LOGIN_SUCCESS: 'Login successful',
  LOGIN_FAILED: 'Login failed',
  FAILED_TO_STORE_OTP: 'Failed to store OTP',
  OTP_SENT_SUCCESSFULLY: 'Otp sent successfully',
  PHONE_NUMBER_EXISTS: 'Phone number already exists',
  USER_NOT_FOUND: 'User not found',
  INVALID_PASSWORD: 'Invalid password',
  OTP_GENERATION_FAILED: 'OTP generation failed',
  PHONE_NUMBER_NOT_FOUND: 'Phone number not found',
  INVALID_OTP: 'Incorrect Otp',
  OTP_EXPIRED: 'Otp expired, request a new one',
  OTP_VERIFIED: 'Otp successfully verified',
  USERNAME_DOES_NOT_EXISTS: 'Username does not exists',
  INVALID_PHONE_NUMBER: 'Invalid phone number',
  EMAIL_MUST_MATCH: 'Email must match the login email.',
};
